<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<OutputPath>bin\Release\net8.0\win-x64\</OutputPath>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
    <BaseOutputPath>C:\ST10439147_CLDV6212_POE\ST10439147_CLDV6212_POE\bin</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.25.1" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.23.0" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.23.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="9.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

</Project>
